name: Build and Release Windows Executables

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual triggering

# Grant permissions to create a release and write to the repository
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild.exe chat_solution/chat_solution.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Executable Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-executables
          path: |
            chat_solution/x64/Release/client_cli.exe
            chat_solution/x64/Release/client_gui.exe
            chat_solution/x64/Release/server_application.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            chat_solution/x64/Release/client_cli.exe
            chat_solution/x64/Release/client_gui.exe
            chat_solution/x64/Release/server_application.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
